version: '3.5'

services:
  webserver:
    image: nginx
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/www/poll4dates/static
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: .
    environment:
      - DB_HOST=database
    command: sh -c "python3 manage.py migrate && python3 manage.py createsuperuser --noinput --name=Admin --email=admin20@example.com && python3 manage.py collectstatic --noinput && gunicorn -b 0.0.0.0:8000 poll4dates.wsgi:application --daemon && daphne -b 0.0.0.0 -p 8001 poll4dates.asgi:application;"
    volumes:
      - ./:/poll4dates
      - static:/var/www/poll4dates/static
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - ./poll4dates/.env
    volumes:
      - ~/data:/var/lib/postgresql/data

volumes:
  static:
