version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/python:3.11.3
    steps:
      - checkout
      - run:
          name: Build
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
workflows:
  default:
    jobs:
      - build
