# Generated by Django 4.2.1 on 2023-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="user",
            new_name="creator",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="event",
        ),
        migrations.AddField(
            model_name="poll",
            name="event_details",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="event_location",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="event_name",
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poll",
            name="event_organizer",
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poll",
            name="event_timezone",
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
