# Generated by Django 4.2.1 on 2023-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="token",
            field=models.CharField(default="ixutuKOQ", max_length=8),
        ),
    ]
