# Generated by Django 4.2.1 on 2023-06-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_poll_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="1O5wfyJO", max_length=8),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=250)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="polls.poll",
                    ),
                ),
            ],
        ),
    ]
