# Generated by Django 4.2.1 on 2023-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_message_sent_at_alter_poll_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["sent_at"]},
        ),
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="Fn8JA8lh", max_length=8),
        ),
    ]
