# Generated by Django 4.2.1 on 2023-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_remove_message_sender_message_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="vI4BnFhy", max_length=8),
        ),
    ]
