# Generated by Django 4.2.1 on 2023-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_alter_poll_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="B9UC0GgG", max_length=8),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                models.F("poll"), models.F("name"), name="unique_name_per_poll"
            ),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                models.F("poll"), models.F("email"), name="unique_email_per_poll"
            ),
        ),
    ]
