# Generated by Django 4.2.1 on 2023-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_alter_poll_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="9bBc2N0x", max_length=8),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                models.F("poll"),
                models.F("name"),
                models.F("email"),
                name="unique_guest_per_poll",
            ),
        ),
    ]
