# Generated by Django 4.2.1 on 2023-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_poll_token_guest_unique_name_per_poll_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="5jD3o0rb", max_length=8),
        ),
    ]
