# Generated by Django 4.2.1 on 2023-08-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_poll_token_guest_unique_guest_per_poll"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="guest",
            name="unique_guest_per_poll",
        ),
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="y55ZjsIU", max_length=8),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                models.F("poll"), models.F("name"), name="unique_name_per_poll"
            ),
        ),
        migrations.AddConstraint(
            model_name="guest",
            constraint=models.UniqueConstraint(
                models.F("poll"), models.F("email"), name="unique_email_per_poll"
            ),
        ),
    ]
