# Generated by Django 4.2.1 on 2023-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_alter_guest_email_alter_poll_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
