# Generated by Django 4.2.1 on 2023-08-15 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_alter_poll_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name="poll",
            name="guid",
            field=models.UUIDField(db_index=True, default=uuid.uuid1),
        ),
    ]
