# Generated by Django 4.2.1 on 2023-08-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_guest_guid_poll_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="token",
            field=models.CharField(default="7rboKv2y", max_length=8),
        ),
    ]
